name: Build Godot Project

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/build"
  pull_request:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: KitchenCorner-0.1.0

jobs:
  Godot:
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-4.1.3
    strategy:
      matrix:
        platform: [windows]
        mode: [release, debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
          cd ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
          ls -l
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform }}
          godot -v --headless --export-${{ matrix.mode }} "${{ matrix.platform }}" build/${{ matrix.platform }}/${EXPORT_NAME}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }} - ${{ matrix.platform }} - ${{ matrix.platform }}
          path: build/${{ matrix.platform }}/